In [2]:
import numpy as np

In [3]:
a = np.array([[1 , 2 , 3 , 4 , 5 , 6 , 7] , [8 , 9 , 10 , 11 , 12 , 13 , 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [2]:
a.shape

NameError: name 'a' is not defined

In [5]:
#Get a specific element [r , c]
a[1 , 5] # 13

13

In [6]:
a[1 , -2]

13

In [8]:
#Get a specific row
a[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
#Get a specific column
a[: , 2]

array([ 3, 10])

In [10]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0 , 1:6:2]

array([2, 4, 6])

In [12]:
a[1 , 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# a[: , 2] = 0
a[: , 2] = [10 , 3]
print(a)