In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#return data type by default it's int32 
print(b.dtype)

int32


In [6]:
#Get dimention
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#Get Shape
a.shape

(3,)

In [9]:
b.shape # 3 * 3 (row , column)

(3, 3)

In [10]:
c = np.array([1 , 2 , 3] , dtype='int16')
c.dtype

dtype('int16')

In [11]:
#Get Size
c.itemsize

2

In [12]:
#Get number of element in the array
c.size

3

In [13]:
#Get total size
# c.size * c.itemsize
c.nbytes

6

In [14]:
nums = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
for row in nums:
    for n in row:
        print(n , end = ' ')
    print()

1 2 3 
4 5 6 
